config/routes.rb
Rails.application.routes.draw do

    #require "admin_constraint"
    require 'sidekiq/web'

    #constraints lambda {|request| AuthConstraint.admin?(request) } do
    mount Sidekiq::Web => '/admin/sidekiq'
  
  devise_for :users, controllers: {
      passwords: 'users/passwords'
  }

  resources :users do
    collection do
      post 'add', to: 'users#create', as: 'add'
    end

    resources :parcels
  end

  resources :parcels do
    collection do
      get 'tracking_code/:code', to: 'parcels#show', as: 'tracking_code'
    end
  end

  # This section generates the URLs for the API endpoints of this app
  # Through this endpoints URLs we expose the data that we want to share to other apps
  namespace :api do
    resources :track_events
    resources :users
  end

  get 'home/index' => 'home#index', as: 'dashboard'
  get 'postcode' => 'postcode#postcode'
  match 'lookup_postcode' => 'postcode#lookup_postcode', via: [:get, :post]
  get 'welcome/faq'
  get 'welcome/about'
  get 'welcome/features'
  get 'welcome/index'
  

  root to: 'welcome#index'
  
end

app/models/parcel.rb
class Parcel #< ApplicationRecord
    include Mongoid::Document
    include Mongoid::Timestamps

    field :user_id, type: String
    field :tracking_code, type: String
    field :origin_address_id, type: String
    field :destination_address_id, type: String  
    field :receiver_name, type: String  
    field :receiver_phone, type: String  
    field :receiver_email, type: String
    field :created_at, type: DateTime
    field :updated_at, type: DateTime
    field :status, type: String

    belongs_to :user
    has_many :track_events

    after_create :push_data_to_tracker

    def origin_address
        address = Address.where(id: origin_address_id).first
        "#{address.street} #{address.ext_number} #{address.int_number}, #{address.city}, #{address.country}"
    end

    def destination_address
        address = Address.find_by(id: destination_address_id)
        "#{address.street} #{address.ext_number} #{address.int_number}, #{address.city}, #{address.country}"
    end

    def push_data_to_tracker
        PushParcelToTrackerJob.perform_later(
            self._id.to_s,
            self.origin_address_id,
            self.destination_address_id
        ) unless Rails.env == 'test'             
    end
end

app/controllers/parcels_controller.rb
class ParcelsController < ApplicationController
    def index    
        @parcels = current_user.admin? ? Parcel.all : current_user.parcels
    end

    def show
        if params[:code]
            @parcel = Parcel.find_by tracking_code: params[:code]
            MarkNotificationAsReadJob.perform_later params[:code]
        else
            @parcel = Parcel.find params[:id]
        end
        @origin_address = Address.find @parcel.origin_address_id
        @destination_address = Address.find @parcel.destination_address_id
    end

    def new
        @parcel = Parcel.new
        @users = User.in(admin: nil)
    end

    def create
        origin = Address.create(origin_address_params)
        destination = Address.create(destination_address_params)

            # Ensure generated tracking code does not exist already
            while true do
                tracking_code = SecureRandom.base64(16).gsub(/\W/, '')
                break unless Parcel.where(tracking_code: tracking_code).length > 0
            end
    
        @parcel = Parcel.new(parcel_params.merge(
            tracking_code: tracking_code,
            origin_address_id: origin._id.to_s,
            destination_address_id: destination._id.to_s,
            status: 'added to system')
        )

        if @parcel.save
            redirect_to parcels_path, notice: 'Item created!'
        else
            render :new, notice: 'Errors'
        end
    end

    private

    def parcel_params
        params.require(:parcel).permit(:user_id, :tracking_code, :receiver_name, :receiver_phone, :receiver_email)
    end

    def origin_address_params
        params.require(:origin_address).permit(:street, :ext_number, :int_number, :city, :country, :zip_code)
    end
    
    def destination_address_params
        params.require(:destination_address).permit(:street, :ext_number, :int_number, :city, :country, :zip_code)
    end

end

app/views/parcels/index.html.erb
<hr>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="col-md-12">
      <% if current_user.admin? %>
        <h4 class="float-left">Parcels</h4><%= link_to 'Create', new_parcel_path, class: 'btn btn-success float-right' %>
      <% else %>
        <h4 class="float-left">Parcels for user <%= current_user.email %></h4>
      <% end %>
    </li>
  </ol>
</nav>

<hr>

<table class="table">
<thead>
<tr>
<th>Tracking code</th>
<% if current_user.admin %>
  <th>Owner</th>
<% end %>
<th>Origin</th>
<th>Destination</th>
<th>Receiver name</th>
<th>Receiver phone</th>
<th>Receiver e-mail</th>
<th>Creation date</th>
</tr>
</thead>
<tbody>
<% @parcels.each do |parcel| %>
    <tr>
    <td><%= link_to parcel.tracking_code, user_parcel_path(current_user.id, parcel.id), class: 'btn btn-warning' %></td>
    <% if current_user.admin %>
        <td><%= parcel.user.email %></td>
    <% end %>
    <td><%= parcel.origin_address %></td>
    <td><%= parcel.destination_address %></td>
    <td><%= parcel.receiver_name %></td>
    <td><%= parcel.receiver_phone %></td>
    <td><%= parcel.receiver_email %></td>
    <td><%= parcel.created_at %></td>
    </tr>
<% end %>
</tbody>
</table>


<br><br><br><br>

<div class= "container text-center">

    <div class="btn-group">
    <%= link_to 'Back to HomePage', '/', :class => "btn btn-primary" %>
    </div>
    
</div>

app/views/parcels/new.html.erb
<hr>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active">
      <h4>Register a parcel</h4>
    </li>
  </ol>
</nav>

<div>
    <%= form_for @parcel do |f| %>
        <div class="form-group col col-md-12">
            <div class="row">
              <%= f.label 'Client' %>
              <div class="col-md-4">
                <%= f.select :user_id, options_from_collection_for_select(@users, :id, :email), {},
                             {class: 'form-control' }
                %>
              </div>
              <div class="col-md-4">
                <%=
                    link_to 'Add user', 'javascript:void(0)', class: 'btn btn-primary btn-sm',
                        data: {toggle: 'modal', target: '#add_user_modal'}
                 %>
              </div>
            </div>
            <br />
            <div class="row">
              <div class="card" style="width: 24rem;">
                <div class="card-body">
                  <h5 class="card-title">Origin Address</h5>
                  <div class="input-group mb-6">
                    <%= field_set_tag nil, style: 'min-width: 100%;' do %>
                        <%= label_tag 'Street'%><br />
                        <%= text_field_tag 'origin_address[street]', nil,  class: 'form-control' %>
                        <%= label_tag 'External number'%><br />
                        <%= text_field_tag 'origin_address[ext_number]', nil,  class: 'form-control' %>
                        <%= label_tag 'Appartment number'%><br />
                        <%= text_field_tag 'origin_address[int_number]', nil,  class: 'form-control' %>
                        <%= label_tag 'City'%><br />
                        <%= text_field_tag 'origin_address[city]', nil,  class: 'form-control' %>
                        <%= label_tag 'Country'%><br />
                        <%= text_field_tag 'origin_address[country]', nil,  class: 'form-control' %>
                        <%= label_tag 'ZIP code'%><br />
                        <%= text_field_tag 'origin_address[zip_code]', nil,  class: 'form-control',
                                           style: 'width: 75%; display:inline-block;' %>
                        <div class="input-group-append" style="display: inline-block; width: 23%;">
                          <%= link_to 'Lookup', 'javascript:void(0);', id: 'source_zipcode', class: 'btn btn-outline-secondary' %>
                        </div>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="card" style="width: 24rem;">
                <div class="card-body">
                  <h5 class="card-title">Destination Address</h5>
                  <div class="input-group mb-6">
                    <%= field_set_tag nil, style: 'min-width: 100%;' do %>
                      <%= label_tag 'Street'%><br />
                      <%= text_field_tag 'destination_address[street]', nil,  class: 'form-control' %>
                      <%= label_tag 'External number'%><br />
                      <%= text_field_tag 'destination_address[ext_number]', nil,  class: 'form-control' %>
                      <%= label_tag 'Appartment number'%><br />
                      <%= text_field_tag 'destination_address[int_number]', nil,  class: 'form-control' %>
                      <%= label_tag 'City'%><br />
                      <%= text_field_tag 'destination_address[city]', nil,  class: 'form-control' %>
                      <%= label_tag 'Country'%><br />
                      <%= text_field_tag 'destination_address[country]', nil,  class: 'form-control' %>
                      <%= label_tag 'ZIP code'%><br />
                      <%= text_field_tag 'destination_address[zip_code]', nil,  class: 'form-control',
                                         style: 'width: 75%; display:inline-block;' %>
                      <div class="input-group-append" style="display: inline-block; width: 23%;">
                        <%= link_to 'Lookup', 'javascript:void(0);', id: 'destination_zipcode', class: 'btn btn-outline-secondary' %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="card" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">Receiver</h5>
                  <%= f.label 'Name' %><br />
                  <%= f.text_field :receiver_name, class: 'form-control' %>
                  <%= f.label 'Phone' %><br />
                  <%= f.phone_field :receiver_phone, class: 'form-control' %>
                  <%= f.label 'E-mail' %><br />
                  <%= f.email_field :receiver_email, class: 'form-control' %>
                </div>
              </div>
            </div>
        </div>

        <div class="actions">
            <%= f.submit "Create", class: 'btn btn-primary' %>
        </div>
    <% end %>
</div>

<%= render 'shared/add_user_modal' %>

<div class= "container text-center">

    <div class="btn-group">
    <%= link_to 'Back to HomePage', '/', :class => "btn btn-primary" %>
    </div>
    
</div>

<script>
  enable_lookup_buttons();
</script>

app/views/parcels/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="col-md-12">
        <h4 class="float-left">Parcel - <%= @parcel.tracking_code %></h4>
    </li>
  </ol>
</nav>

<div class="row">
<div class="col-md-12">
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Receiver: <%= @parcel.receiver_name %></h5>
    <hr>
    <div class="row">Phone: <%= @parcel.receiver_phone %></div>
    <div class="row">e-mail: <%= @parcel.receiver_email %></div>
  </div>

</div>
</div>
</div>

<hr>

<div class="row">
  <div class="col-sm-6">
    <div class="card" style="width: 34rem;">
          <div class="card-body">
            <h5 class="card-title">Origin Address</h5>
            <hr>
            <div>
              <p><strong>Street:</strong>&nbsp;<%= @origin_address.street %></p>
              <p><strong>External number:</strong>&nbsp;<%= @origin_address.ext_number %></p>
              <p><strong>Appartment:</strong>&nbsp;<%= @origin_address.int_number %></p>
              <p><strong>City:</strong>&nbsp;<%= @origin_address.city %></p>
              <p><strong>Country:</strong>&nbsp;<%= @origin_address.country %></p>
              <p><strong>ZIP code:</strong>&nbsp;<%= @origin_address.zip_code %></p>
            </div>
          </div>

    </div>
  </div>
  <div class="col-sm-6">
    <div class="card" style="width: 34rem;">
          <div class="card-body">
            <h5 class="card-title">Destination Address</h5>
            <hr>
            <div>
              <p><strong>Street:</strong>&nbsp;<%= @destination_address.street %></p>
              <p><strong>External number:</strong>&nbsp;<%= @destination_address.ext_number %></p>
              <p><strong>Appartment:</strong>&nbsp;<%= @destination_address.int_number %></p>
              <p><strong>City:</strong>&nbsp;<%= @destination_address.city %></p>
              <p><strong>Country:</strong>&nbsp;<%= @destination_address.country %></p>
              <p><strong>ZIP code:</strong>&nbsp;<%= @destination_address.zip_code %></p>
            </div>
          </div>
    </div>
  </div>

</div>
<hr>
<h3>Tracking History</h3>
<table class="table">
    <thead>
      <tr>
        <th>Date</th>
        <th>Location</td>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
        <tr>
            <td><%= @parcel.created_at %></td>
            <td>&nbsp;</td>
            <td>Added into the system</td>
        </tr>
        <% @parcel.track_events.each do |event| %>
            <tr>
                <td><%= event.created_at %></td>
                <td><%= event.location %></td>
                <td><%= event.description %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'Back', root_path, class: 'btn btn-primary' %>


<% if params[:code] %>
    <script>
        document.location = "/parcels/<%= @parcel.id %>"
    </script>
<% end %>