config/routes.rb
Rails.application.routes.draw do

    #require "admin_constraint"
    require 'sidekiq/web'

    #constraints lambda {|request| AuthConstraint.admin?(request) } do
    mount Sidekiq::Web => '/admin/sidekiq'
  
  devise_for :users, controllers: {
      passwords: 'users/passwords'
  }

  resources :users do
    collection do
      post 'add', to: 'users#create', as: 'add'
    end

    resources :parcels
  end

  resources :parcels do
    collection do
      get 'tracking_code/:code', to: 'parcels#show', as: 'tracking_code'
    end
  end

  # This section generates the URLs for the API endpoints of this app
  # Through this endpoints URLs we expose the data that we want to share to other apps
  namespace :api do
    resources :track_events
    resources :users
  end

  get 'home/index' => 'home#index', as: 'dashboard'
  get 'postcode' => 'postcode#postcode'
  match 'lookup_postcode' => 'postcode#lookup_postcode', via: [:get, :post]
  get 'welcome/faq'
  get 'welcome/about'
  get 'welcome/features'
  get 'welcome/index'
  

  root to: 'welcome#index'
  
end

app/controllers/postcode.rb
require 'postcode_api'

class PostcodeController < ApplicationController
    before_action :user_signed_in?

  # Get /postcode
  
  def index
    retrieve_data
    render "postcode/index"
  end

  # Get /postcode
 
  def show
  end
end

app/controllers/postcode_controller.rb
require 'postcode_api'

class PostcodeController < ApplicationController
  before_action :user_signed_in?

  # Get /postcode
  
  def postcode
  
  end

  # Post /lookup_postcode
 
  def lookup_postcode
    if params[:symbol].present?
      @response = Postcode::HTTP.ticker_data(params[:symbol].
        gsub(' ', '+').gsub(',',''))['results']
    end

    respond_to do |format|
      format.html
      format.json do
        render json: { result: @response }, status: :ok
      end
    end
  end

end

app/views/postcode/_form.html.erb
<hr>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active">
      <h4>Lookup address</h4>
    </li>
  </ol>
</nav>

<%= form_tag lookup_postcode_path, method: :post do %>
  <div class="row">
    <div class="col-md-4">
      <%= text_field_tag 'symbol', nil, placeholder: 'Enter Address', size: 40, class: 'form-control' %>
    </div>
    <div class="col-md-4">
      <%= submit_tag 'Validate', class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/postcode/lookup_postcode.html.erb
<%= render 'form' %>

<br/>

<% if @response %>
    <% idx = 1 %>
    <% @response.each do |item| %>
      <div class="card" style="width: 36rem;">
        <div class="card-body">
          <h5 class="card-title">Result <%= idx %></h5>
          <hr>
          <div class="col-sm-12">
            <%= item['formatted_address'] %>
          </div>
        </div>
      </div>
      <% idx += 1 %>
    <% end %>
 <% end %>

<br/>

<div class= "container text-center">

    <div class="btn-group">
    <%= link_to 'Back to HomePage', '/', :class => "btn btn-primary" %>
    </div>
    
</div>

app/views/postcode/postcode.html.erb
<%= render 'form' %>


<br><br><br><br>

<div class= "container text-center">

    <div class="btn-group">
    <%= link_to 'Back to HomePage', '/', :class => "btn btn-primary" %>
    </div>
    
</div>