config/routes.rb
Rails.application.routes.draw do

    #require "admin_constraint"
    require 'sidekiq/web'

    #constraints lambda {|request| AuthConstraint.admin?(request) } do
    mount Sidekiq::Web => '/admin/sidekiq'
  
  devise_for :users, controllers: {
      passwords: 'users/passwords'
  }

  resources :users do
    collection do
      post 'add', to: 'users#create', as: 'add'
    end

    resources :parcels
  end

  resources :parcels do
    collection do
      get 'tracking_code/:code', to: 'parcels#show', as: 'tracking_code'
    end
  end

  # This section generates the URLs for the API endpoints of this app
  # Through this endpoints URLs we expose the data that we want to share to other apps
  namespace :api do
    resources :track_events
    resources :users
  end

  get 'home/index' => 'home#index', as: 'dashboard'
  get 'postcode' => 'postcode#postcode'
  match 'lookup_postcode' => 'postcode#lookup_postcode', via: [:get, :post]
  get 'welcome/faq'
  get 'welcome/about'
  get 'welcome/features'
  get 'welcome/index'
  

  root to: 'welcome#index'
  
end

app/views/shared/_add_user_modal.html.erb
<div class="modal" tabindex="-1" role="dialog", id="add_user_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">New User</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'shared/new_user_form' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_new_user_form.html.erb
<div class="form-box col-md-12">

  <%= form_for(User.new, url: add_users_path, method: :post) do |f| %>

    <div class="form-group">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control' %>
    </div>

    <div class="actions">
      <%= f.submit "Save", class: 'btn btn-primary' %>
    </div>
  <% end %>

</div>