config/routes.rb
Rails.application.routes.draw do

    #require "admin_constraint"
    require 'sidekiq/web'

    #constraints lambda {|request| AuthConstraint.admin?(request) } do
    mount Sidekiq::Web => '/admin/sidekiq'
  
  devise_for :users, controllers: {
      passwords: 'users/passwords'
  }

  resources :users do
    collection do
      post 'add', to: 'users#create', as: 'add'
    end

    resources :parcels
  end

  resources :parcels do
    collection do
      get 'tracking_code/:code', to: 'parcels#show', as: 'tracking_code'
    end
  end

  # This section generates the URLs for the API endpoints of this app
  # Through this endpoints URLs we expose the data that we want to share to other apps
  namespace :api do
    resources :track_events
    resources :users
  end

  get 'home/index' => 'home#index', as: 'dashboard'
  get 'postcode' => 'postcode#postcode'
  match 'lookup_postcode' => 'postcode#lookup_postcode', via: [:get, :post]
  get 'welcome/faq'
  get 'welcome/about'
  get 'welcome/features'
  get 'welcome/index'
  

  root to: 'welcome#index'
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        if current_user.admin
            @parcels = Parcel.all
        else
            @parcels = current_user.parcels
        end
    end
    
end

app/views/home/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="col-md-12">
        <h4 class="float-left">Welcome <%= current_user.email %></h4>
    </li>
  </ol>
</nav>


<div class="row">
  <div class="col-sm-3">
  </div>
  <div class="col-sm-3">
    <%= link_to 'Dashboard', user_parcels_path(current_user), class: 'btn btn-warning' %>
  </div>
  <div class="col-sm-3">
    <%= link_to 'Validate location', postcode_path, class:'btn btn-warning' %>
  </div>
  <div class="col-sm-3">
  </div>
</div>

<hr>

<div class="accordion" id="accordionExample">
  <% idx = 0 %>
  <% @parcels.each do |parcel| %>
    <div class="card">
      <div class="card-header" id="heading-<%= parcel.tracking_code %>">
        <h2 class="mb-0">
          <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse-<%= parcel.tracking_code %>" aria-expanded="true" aria-controls="collapse-<%= parcel.tracking_code %>">
            <%= link_to parcel.tracking_code, 'javascript:void(0);', class: 'btn btn-warning' %>
          </button>
        </h2>
      </div>

      <div id="collapse-<%= parcel.tracking_code %>" class="collapse <%= 'show' == 0 %>" aria-labelledby="heading-<%= parcel.tracking_code %>" data-parent="#accordionExample">
        <div class="card-body">
          <table class="table">
          <tbody>
          <% parcel.track_events.each do |event| %>
              <tr>
                <td><%= event.created_at %></td>
                <td><%= event.location %></td>
                <td><%= event.description %></td>
              </tr>
          <% end %>  
          </tbody>
          </table>
        </div>
      </div>
    </div>
    <% idx += 1 %>
  <% end %>  
</div>

<hr>